-- MySQL Script generated by MySQL Workbench
-- Sat May 27 01:41:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `emsdb` ;

-- -----------------------------------------------------
-- Schema emsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emsdb` DEFAULT CHARACTER SET utf8 ;
USE `emsdb` ;

-- -----------------------------------------------------
-- Table `emsdb`.`absent_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emsdb`.`absent_request` ;

CREATE TABLE IF NOT EXISTS `emsdb`.`absent_request` (
  `absent_request_id` BIGINT NOT NULL AUTO_INCREMENT,
  `absent_requestcol` VARCHAR(45) NULL,
  `employee_id` BIGINT NOT NULL,
  `date` DATE NULL,
  `leave_time` INT NULL,
  PRIMARY KEY (`absent_request_id`),
  INDEX `fk_absent_request_employee_profile1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_absent_request_employee_profile1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `emsdb`.`employee_profile` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emsdb`.`attendance_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emsdb`.`attendance_record` ;

CREATE TABLE IF NOT EXISTS `emsdb`.`attendance_record` (
  `attendance_record_id` BIGINT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NOT NULL,
  `date` DATE NOT NULL,
  `time` INT NOT NULL,
  PRIMARY KEY (`attendance_record_id`),
  INDEX `fk_table1_employee_profile1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_table1_employee_profile1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `emsdb`.`employee_profile` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emsdb`.`employee_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emsdb`.`employee_profile` ;

CREATE TABLE IF NOT EXISTS `emsdb`.`employee_profile` (
  `employee_id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emsdb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emsdb`.`project` ;

CREATE TABLE IF NOT EXISTS `emsdb`.`project` (
  `project_id` BIGINT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NOT NULL,
  `manager_id` BIGINT NULL,
  `project_name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `type` VARCHAR(45) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `grade` INT NULL,
  `feedback` VARCHAR(500) NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_employee_profile1_idx` (`employee_id` ASC),
  INDEX `fk_project_employee_profile2_idx` (`manager_id` ASC),
  CONSTRAINT `fk_project_employee_profile1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `emsdb`.`employee_profile` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_employee_profile2`
    FOREIGN KEY (`manager_id`)
    REFERENCES `emsdb`.`employee_profile` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emsdb`.`verification_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emsdb`.`verification_report` ;

CREATE TABLE IF NOT EXISTS `emsdb`.`verification_report` (
  `verification_report_id` BIGINT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NOT NULL,
  `reporter_name` VARCHAR(45) NULL,
  `report_date` DATETIME NULL,
  `comment` VARCHAR(500) NULL,
  PRIMARY KEY (`verification_report_id`),
  INDEX `fk_verification_report_employee_profile1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_verification_report_employee_profile1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `emsdb`.`employee_profile` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
